/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection {
  'bio' : string,
  'tagline' : string,
  'lastUpdated' : Timestamp,
  'portraitImage' : Image,
}
export interface ContactSubmission {
  'name' : string,
  'email' : Email,
  'message' : string,
  'timestamp' : Timestamp,
}
export type Email = string;
export type Image = Uint8Array;
export type PortfolioCategory = { 'landscapes' : null } |
  { 'commercial' : null } |
  { 'other' : string } |
  { 'events' : null } |
  { 'weddings' : null } |
  { 'portraits' : null };
export interface PortfolioItem {
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'category' : PortfolioCategory,
  'image' : Image,
}
export type Price = string;
export interface ServicePackage {
  'features' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'price' : Price,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolioItem' : ActorMethod<[string, string, string, Image], bigint>,
  'createServicePackage' : ActorMethod<
    [string, string, Price, Array<string>],
    bigint
  >,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteServicePackage' : ActorMethod<[bigint], undefined>,
  'getAboutSection' : ActorMethod<[], [] | [AboutSection]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getContactSubmissionsCount' : ActorMethod<[], bigint>,
  'getPortfolioCount' : ActorMethod<[], bigint>,
  'getPortfolioItem' : ActorMethod<[bigint], [] | [PortfolioItem]>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getPortfolioItemsByCategory' : ActorMethod<
    [PortfolioCategory],
    Array<PortfolioItem>
  >,
  'getServicePackage' : ActorMethod<[bigint], [] | [ServicePackage]>,
  'getServicePackages' : ActorMethod<[], Array<ServicePackage>>,
  'getServicePackagesCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContactForm' : ActorMethod<[string, Email, string], undefined>,
  'updateAboutSection' : ActorMethod<[string, string, Image], undefined>,
  'updatePortfolioItem' : ActorMethod<[bigint, PortfolioItem], undefined>,
  'updateServicePackage' : ActorMethod<[bigint, ServicePackage], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];