/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Image = IDL.Vec(IDL.Nat8);
export const Price = IDL.Text;
export const Timestamp = IDL.Int;
export const AboutSection = IDL.Record({
  'bio' : IDL.Text,
  'tagline' : IDL.Text,
  'lastUpdated' : Timestamp,
  'portraitImage' : Image,
});
export const Email = IDL.Text;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : Email,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const PortfolioCategory = IDL.Variant({
  'landscapes' : IDL.Null,
  'commercial' : IDL.Null,
  'other' : IDL.Text,
  'events' : IDL.Null,
  'weddings' : IDL.Null,
  'portraits' : IDL.Null,
});
export const PortfolioItem = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'category' : PortfolioCategory,
  'image' : Image,
});
export const ServicePackage = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'price' : Price,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Image],
      [IDL.Nat],
      [],
    ),
  'createServicePackage' : IDL.Func(
      [IDL.Text, IDL.Text, Price, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'deleteServicePackage' : IDL.Func([IDL.Nat], [], []),
  'getAboutSection' : IDL.Func([], [IDL.Opt(AboutSection)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getContactSubmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortfolioCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioItem)], ['query']),
  'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getPortfolioItemsByCategory' : IDL.Func(
      [PortfolioCategory],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getServicePackage' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ServicePackage)],
      ['query'],
    ),
  'getServicePackages' : IDL.Func([], [IDL.Vec(ServicePackage)], ['query']),
  'getServicePackagesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, Email, IDL.Text], [], []),
  'updateAboutSection' : IDL.Func([IDL.Text, IDL.Text, Image], [], []),
  'updatePortfolioItem' : IDL.Func([IDL.Nat, PortfolioItem], [], []),
  'updateServicePackage' : IDL.Func([IDL.Nat, ServicePackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Image = IDL.Vec(IDL.Nat8);
  const Price = IDL.Text;
  const Timestamp = IDL.Int;
  const AboutSection = IDL.Record({
    'bio' : IDL.Text,
    'tagline' : IDL.Text,
    'lastUpdated' : Timestamp,
    'portraitImage' : Image,
  });
  const Email = IDL.Text;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : Email,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const PortfolioCategory = IDL.Variant({
    'landscapes' : IDL.Null,
    'commercial' : IDL.Null,
    'other' : IDL.Text,
    'events' : IDL.Null,
    'weddings' : IDL.Null,
    'portraits' : IDL.Null,
  });
  const PortfolioItem = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'category' : PortfolioCategory,
    'image' : Image,
  });
  const ServicePackage = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'price' : Price,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Image],
        [IDL.Nat],
        [],
      ),
    'createServicePackage' : IDL.Func(
        [IDL.Text, IDL.Text, Price, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'deleteServicePackage' : IDL.Func([IDL.Nat], [], []),
    'getAboutSection' : IDL.Func([], [IDL.Opt(AboutSection)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getContactSubmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortfolioCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortfolioItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getPortfolioItemsByCategory' : IDL.Func(
        [PortfolioCategory],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getServicePackage' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServicePackage)],
        ['query'],
      ),
    'getServicePackages' : IDL.Func([], [IDL.Vec(ServicePackage)], ['query']),
    'getServicePackagesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, Email, IDL.Text], [], []),
    'updateAboutSection' : IDL.Func([IDL.Text, IDL.Text, Image], [], []),
    'updatePortfolioItem' : IDL.Func([IDL.Nat, PortfolioItem], [], []),
    'updateServicePackage' : IDL.Func([IDL.Nat, ServicePackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };