/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Email = string;
export type Timestamp = bigint;
export type PortfolioCategory = {
    __kind__: "landscapes";
    landscapes: null;
} | {
    __kind__: "commercial";
    commercial: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "events";
    events: null;
} | {
    __kind__: "weddings";
    weddings: null;
} | {
    __kind__: "portraits";
    portraits: null;
};
export interface ContactSubmission {
    name: string;
    email: Email;
    message: string;
    timestamp: Timestamp;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PortfolioItem {
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: PortfolioCategory;
    image: Image;
}
export type Image = Uint8Array;
export interface AboutSection {
    bio: string;
    tagline: string;
    lastUpdated: Timestamp;
    portraitImage: Image;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ServicePackage {
    features: Array<string>;
    name: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    price: Price;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Price = string;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPortfolioItem(title: string, category: string, description: string, image: Image): Promise<bigint>;
    createServicePackage(name: string, description: string, price: Price, features: Array<string>): Promise<bigint>;
    deletePortfolioItem(id: bigint): Promise<void>;
    deleteServicePackage(id: bigint): Promise<void>;
    getAboutSection(): Promise<AboutSection | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getContactSubmissionsCount(): Promise<bigint>;
    getPortfolioCount(): Promise<bigint>;
    getPortfolioItem(id: bigint): Promise<PortfolioItem | null>;
    getPortfolioItems(): Promise<Array<PortfolioItem>>;
    getPortfolioItemsByCategory(category: PortfolioCategory): Promise<Array<PortfolioItem>>;
    getServicePackage(id: bigint): Promise<ServicePackage | null>;
    getServicePackages(): Promise<Array<ServicePackage>>;
    getServicePackagesCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    submitContactForm(name: string, email: Email, message: string): Promise<void>;
    updateAboutSection(bio: string, tagline: string, portraitImage: Image): Promise<void>;
    updatePortfolioItem(id: bigint, updated: PortfolioItem): Promise<void>;
    updateServicePackage(id: bigint, updated: ServicePackage): Promise<void>;
}
import type { AboutSection as _AboutSection, Image as _Image, PortfolioCategory as _PortfolioCategory, PortfolioItem as _PortfolioItem, ServicePackage as _ServicePackage, Timestamp as _Timestamp, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPortfolioItem(arg0: string, arg1: string, arg2: string, arg3: Image): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolioItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolioItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createServicePackage(arg0: string, arg1: string, arg2: Price, arg3: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createServicePackage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServicePackage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deletePortfolioItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioItem(arg0);
            return result;
        }
    }
    async deleteServicePackage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServicePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServicePackage(arg0);
            return result;
        }
    }
    async getAboutSection(): Promise<AboutSection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutSection();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutSection();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getContactSubmissionsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissionsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissionsCount();
            return result;
        }
    }
    async getPortfolioCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioCount();
            return result;
        }
    }
    async getPortfolioItem(arg0: bigint): Promise<PortfolioItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioItem(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioItem(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioItems(): Promise<Array<PortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioItems();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioItems();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioItemsByCategory(arg0: PortfolioCategory): Promise<Array<PortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioItemsByCategory(to_candid_PortfolioCategory_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioItemsByCategory(to_candid_PortfolioCategory_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicePackage(arg0: bigint): Promise<ServicePackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicePackage(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicePackage(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicePackages(): Promise<Array<ServicePackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicePackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicePackages();
            return result;
        }
    }
    async getServicePackagesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicePackagesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicePackagesCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: Email, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAboutSection(arg0: string, arg1: string, arg2: Image): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAboutSection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAboutSection(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePortfolioItem(arg0: bigint, arg1: PortfolioItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioItem(arg0, to_candid_PortfolioItem_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioItem(arg0, to_candid_PortfolioItem_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateServicePackage(arg0: bigint, arg1: ServicePackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServicePackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServicePackage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PortfolioCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioCategory): PortfolioCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioItem_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioItem): PortfolioItem {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AboutSection]): AboutSection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioItem]): PortfolioItem | null {
    return value.length === 0 ? null : from_candid_PortfolioItem_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServicePackage]): ServicePackage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    category: _PortfolioCategory;
    image: _Image;
}): {
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: PortfolioCategory;
    image: Image;
} {
    return {
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: from_candid_PortfolioCategory_n16(_uploadFile, _downloadFile, value.category),
        image: value.image
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    landscapes: null;
} | {
    commercial: null;
} | {
    other: string;
} | {
    events: null;
} | {
    weddings: null;
} | {
    portraits: null;
}): {
    __kind__: "landscapes";
    landscapes: null;
} | {
    __kind__: "commercial";
    commercial: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "events";
    events: null;
} | {
    __kind__: "weddings";
    weddings: null;
} | {
    __kind__: "portraits";
    portraits: null;
} {
    return "landscapes" in value ? {
        __kind__: "landscapes",
        landscapes: value.landscapes
    } : "commercial" in value ? {
        __kind__: "commercial",
        commercial: value.commercial
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "events" in value ? {
        __kind__: "events",
        events: value.events
    } : "weddings" in value ? {
        __kind__: "weddings",
        weddings: value.weddings
    } : "portraits" in value ? {
        __kind__: "portraits",
        portraits: value.portraits
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioItem>): Array<PortfolioItem> {
    return value.map((x)=>from_candid_PortfolioItem_n14(_uploadFile, _downloadFile, x));
}
function to_candid_PortfolioCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioCategory): _PortfolioCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioItem_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioItem): _PortfolioItem {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: PortfolioCategory;
    image: Image;
}): {
    title: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    category: _PortfolioCategory;
    image: _Image;
} {
    return {
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: to_candid_PortfolioCategory_n19(_uploadFile, _downloadFile, value.category),
        image: value.image
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "landscapes";
    landscapes: null;
} | {
    __kind__: "commercial";
    commercial: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "events";
    events: null;
} | {
    __kind__: "weddings";
    weddings: null;
} | {
    __kind__: "portraits";
    portraits: null;
}): {
    landscapes: null;
} | {
    commercial: null;
} | {
    other: string;
} | {
    events: null;
} | {
    weddings: null;
} | {
    portraits: null;
} {
    return value.__kind__ === "landscapes" ? {
        landscapes: value.landscapes
    } : value.__kind__ === "commercial" ? {
        commercial: value.commercial
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "events" ? {
        events: value.events
    } : value.__kind__ === "weddings" ? {
        weddings: value.weddings
    } : value.__kind__ === "portraits" ? {
        portraits: value.portraits
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
